In [1]:
import numpy as np

In [2]:
# 5. How to get the documentation of the numpy add function from the command line?

np.info(np.add)
help(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [3]:
# 6. Create a null vector of size 10 but the fifth value which is 1

arr = np.zeros(5)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1.]


In [4]:
# 7. Create a vector with values ranging from 10 to 49
vect = np.arange(10, 50)
print(vect)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
# 8. Reverse a vector (first element becomes last) 
reverse1 = vect[::-1]
print(reverse1)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [6]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3,3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
idx = np.array([1,2,0,0,4,0])

print(np.nonzero(idx))

(array([0, 1, 4]),)


In [8]:
# 11. Create a 3x3 identity matrix
ident_matrix = np.eye(3)
print(ident_matrix)

# option 2

I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# 12. Create a 3x3x3 array with random values

random_arr = np.random.random((3,4,3))
print(random_arr)

[[[0.56354418 0.12435804 0.61117071]
  [0.18560065 0.92960786 0.11666179]
  [0.02954853 0.73495544 0.09074347]
  [0.58153526 0.25041306 0.34233176]]

 [[0.45152902 0.68697137 0.57055886]
  [0.34098098 0.25780963 0.41014145]
  [0.24753882 0.31103502 0.02629198]
  [0.58238927 0.3327903  0.1038731 ]]

 [[0.88592471 0.0434329  0.39822924]
  [0.5124447  0.15832559 0.98979099]
  [0.17079262 0.5132574  0.42352882]
  [0.27719323 0.40259224 0.08776832]]]


In [10]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values 

mx_min_arr = np.random.random((10,10))
print(mx_min_arr)

print("Min value is: ", mx_min_arr.min())
print("Max value is: ", mx_min_arr.max())


[[0.68221816 0.98830527 0.39847986 0.41195482 0.8882971  0.01127088
  0.22699479 0.61898347 0.70428144 0.76023298]
 [0.32981569 0.99040449 0.80368266 0.51277767 0.75756771 0.66951318
  0.03214318 0.53248221 0.0224698  0.33598654]
 [0.70629142 0.00875206 0.97906323 0.71531079 0.78651048 0.52191987
  0.44898469 0.22745083 0.80992074 0.40854618]
 [0.08280296 0.33918386 0.41572039 0.83676157 0.1173815  0.91892251
  0.44636926 0.25310614 0.53440049 0.9554768 ]
 [0.80207721 0.0323475  0.13740612 0.35626536 0.42251717 0.9067819
  0.32234544 0.18292102 0.53498264 0.60878134]
 [0.76193874 0.97172885 0.24918521 0.02965104 0.14030072 0.69441677
  0.95957011 0.5115889  0.191722   0.00549316]
 [0.2590638  0.46616129 0.0961622  0.83401178 0.19843343 0.87342243
  0.51844602 0.70137197 0.46036255 0.0083885 ]
 [0.23572007 0.66048611 0.08389131 0.62268315 0.09796751 0.98368037
  0.64568721 0.66419503 0.07816345 0.47346487]
 [0.73660534 0.11013775 0.44578218 0.30605657 0.88737565 0.17158911
  0.60932343 

In [11]:
# 14. Create a random vector of size 30 and find the mean value

ran_vec = np.random.random((30))
print(ran_vec)

print("min vector value is: ", ran_vec.min())

[0.67803131 0.16213816 0.15485198 0.16626175 0.99453971 0.96992332
 0.65195791 0.02550923 0.13428717 0.41182729 0.90908574 0.65487881
 0.58260051 0.56018464 0.71038367 0.4583451  0.12125186 0.39304665
 0.96720149 0.00710436 0.61700809 0.41990262 0.61747561 0.62434322
 0.54212034 0.63602198 0.60511613 0.64599842 0.34845172 0.14594092]
min vector value is:  0.007104364985651368


In [12]:
# 15. Create a 2d array with 1 on the border and 0 inside

twoDarr = np.ones((5,5))

twoDarr[1:-1, 1:-1] = 0
print(twoDarr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
# 16. How to add a border (filled with 0's) around an existing array?
twoD = np.zeros((5,5))
print(twoD)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
diag = np.diag([1,2,3,4], k= -1)
print(diag)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [15]:
# 18  Create a 8x8 matrix and fill it with a checkerboard pattern

checkboard = np.zeros((8,8), dtype= int)
checkboard[::2, ::2] = 1
checkboard[1::2, 1::2] = 1
print(checkboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [16]:
# another way

cbd = np.indices((8,8)).sum(axis= 0) % 2
print(cbd)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [17]:
# 20 Create a checkerboard 8x8 matrix using the tile function

tileprob = np.array([[1,0],
					[0,1]])
answ = np.tile(tileprob, (8,8))
print(answ)

[[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]]


In [18]:
# 21 Normalize a 5x5 random matrix 
orgarr = np.random.random((5,5))

norarr = (orgarr - orgarr.min() / orgarr.max() - orgarr.min())


print("Original Array: ", orgarr)
print("\nNormalized Array: ", norarr)


Original Array:  [[0.04390094 0.38976092 0.82305955 0.38895108 0.53777732]
 [0.26021655 0.62942074 0.40303119 0.48738218 0.92313045]
 [0.57011709 0.84641182 0.41184888 0.6602763  0.15559274]
 [0.13392544 0.53181188 0.06493339 0.13661657 0.36410083]
 [0.2404392  0.01669111 0.01493045 0.14791466 0.58871929]]

Normalized Array:  [[ 0.01279678  0.35865675  0.79195539  0.35784692  0.50667316]
 [ 0.22911239  0.59831658  0.37192703  0.45627802  0.89202628]
 [ 0.53901293  0.81530765  0.38074471  0.62917213  0.12448858]
 [ 0.10282128  0.50070772  0.03382923  0.10551241  0.33299667]
 [ 0.20933504 -0.01441305 -0.01617371  0.1168105   0.55761512]]


In [19]:
# 23

color_dtype = np.dtype([
	('R', np.uint8),
	('G', np.uint8),
	('B', np.uint8),
	('A', np.uint8)
])

In [20]:
color = np.array((255, 128, 64, 255), dtype= color_dtype)
print(color)

(255, 128, 64, 255)


In [21]:
print(color['R'])

255


In [22]:
# 24 Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

m1 = np.random.random((5, 3))
m2 = np.random.random((3, 2))

res = np.dot(m1, m2)

print("Matrix A: ", m1)
print("Matrix B: ", m2)
print("Matrix product: ", res)

Matrix A:  [[0.57759258 0.55426803 0.88357644]
 [0.67928735 0.07912633 0.70830747]
 [0.7093809  0.5433114  0.94260829]
 [0.61208982 0.18477877 0.78531445]
 [0.1200105  0.92169583 0.6471436 ]]
Matrix B:  [[0.59272652 0.82093048]
 [0.07551432 0.42582448]
 [0.27858551 0.88560828]]
Matrix product:  [[0.63036121 1.49268686]
 [0.605931   1.21862458]
 [0.72409367 1.64848941]
 [0.59553254 1.27664749]
 [0.32101946 1.06411666]]


In [23]:
# 25 
arrneg = np.array([1, 4, 6, 9, 2, 7, 8, 3])

arrneg[(arrneg > 3) & (arrneg < 8)] *= -1

print(arrneg)


[ 1 -4 -6  9  2 -7  8  3]


In [24]:
# 27

z = np.array([1,2,3])

print(z**z) # legal

[ 1  4 27]


In [25]:
# 28

test = np.array([np.nan]).astype(int).astype(float)

print(test)

[-9.22337204e+18]


C:\Users\santosh\AppData\Local\Temp\ipykernel_8724\1949928742.py:3: RuntimeWarning: invalid value encountered in cast
  test = np.array([np.nan]).astype(int).astype(float)


In [26]:
# 29
roundarr = np.array([1.2, -2.1, 3.1, -4.2, 2.3, -1.1])

rounded = np.sign(roundarr) * np.ceil(np.abs(roundarr))

print(rounded)

[ 2. -3.  4. -5.  3. -2.]


In [27]:
# 30
A = np.array([1,2,9,8,5])
B = np.array([6,7,8,9,10])

common = np.intersect1d(A, B)
print(common)

[8 9]


In [28]:
# 31 How to ignore all numpy warnings (not recommended)?
# ignp = np.seterr(all='ignore')

from datetime import date, timedelta

In [29]:


today = date.today()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday: ",yesterday)
print("Today: ",today)
print("Tomorrow: ",tomorrow)

Yesterday:  2026-02-04
Today:  2026-02-05
Tomorrow:  2026-02-06


In [30]:
# 34 How to get all the dates corresponding to the month of July 2016?
start = date(2016, 7, 1)
end = date(2016, 8, 1)

dates = []
current = start

while (current < end):
	dates.append(current)
	current += timedelta(days=1)

print(dates)

[datetime.date(2016, 7, 1), datetime.date(2016, 7, 2), datetime.date(2016, 7, 3), datetime.date(2016, 7, 4), datetime.date(2016, 7, 5), datetime.date(2016, 7, 6), datetime.date(2016, 7, 7), datetime.date(2016, 7, 8), datetime.date(2016, 7, 9), datetime.date(2016, 7, 10), datetime.date(2016, 7, 11), datetime.date(2016, 7, 12), datetime.date(2016, 7, 13), datetime.date(2016, 7, 14), datetime.date(2016, 7, 15), datetime.date(2016, 7, 16), datetime.date(2016, 7, 17), datetime.date(2016, 7, 18), datetime.date(2016, 7, 19), datetime.date(2016, 7, 20), datetime.date(2016, 7, 21), datetime.date(2016, 7, 22), datetime.date(2016, 7, 23), datetime.date(2016, 7, 24), datetime.date(2016, 7, 25), datetime.date(2016, 7, 26), datetime.date(2016, 7, 27), datetime.date(2016, 7, 28), datetime.date(2016, 7, 29), datetime.date(2016, 7, 30), datetime.date(2016, 7, 31)]


In [31]:
# 36  Extract the integer part of a random array of positive numbers using 4 different methods
arr = np.random.random(5) * 10
print(arr)

[4.75422819 1.90216509 7.52038249 2.73231743 8.37479896]


In [32]:
# 1. using floor

arrfloor = np.floor(arr)
print(arrfloor)

# 2. using astype

arrtype = arr.astype(int)
print(arrtype)


[4. 1. 7. 2. 8.]
[4 1 7 2 8]


In [33]:
# 3. using trunc

arrtrunc = np.trunc(arr)

print(arrtrunc)

[4. 1. 7. 2. 8.]


In [34]:
# 4. using int divison

arrdivision = arr // 1

print(arrdivision)

[4. 1. 7. 2. 8.]


In [35]:
# 37 Create a 5x5 matrix with row values ranging from 0 to 4 

arrtile = np.tile(np.arange(5), (5,1))
print(arrtile)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [36]:
# 38 Consider a generator function that generates 10 integers and use it to build an array
def gen_gerenter():
	for i in range(10):
		yield i

In [37]:
gen_num = np.fromiter(gen_gerenter(), dtype=int)
print(gen_num)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
# 39
vec = np.linspace(0, 1, 12)[1:-1]
print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [39]:
# 40 Create a random vector of size 10 and sort it

rvec = np.random.random(10)
srt = np.sort(rvec)

print("Original array: ",rvec)
print("Sorted array: ",srt)

Original array:  [0.15275463 0.53320383 0.09640469 0.17429998 0.18454217 0.84810319
 0.36197937 0.72253201 0.9403874  0.30140998]
Sorted array:  [0.09640469 0.15275463 0.17429998 0.18454217 0.30140998 0.36197937
 0.53320383 0.72253201 0.84810319 0.9403874 ]


In [40]:
# 41  How to sum a small array faster than np.sum?

samplearr = np.array([1,2,3,4,5])

# using numpy
npsum = np.sum(samplearr)
print(npsum)

# using built-in 
bisum = sum(samplearr)
print(bisum)

15
15


In [42]:
# 42 Consider two random arrays A and B, check if they are equal

A = np.random.random(5)
B = np.random.random(5)

isequal = np.allclose(A, B)

print(isequal)

False


In [ ]:
# 43 Make an array immutable (read-only) 

arr = np.array([1,2,3,4,5])
imutable = arr.flags.writeable = False


False
